### DISCUSSION TITLE
Tom and Jerry (1940-1960)

### DISCUSSION THREAD

**Discussion by flameshikari** [mach64/trakt-scrobbler#318] [Rewrite rules]
Amazing tool! Thank you very much for it.

So, I thought it would be nice if you created a category in Discussions to allow people to share custom rules for specific shows/movies to save time writing rules in case if someone else has already done it. For example, here's what I did for 'Tom and Jerry':

```toml
[[rules]]
match.title = "Tom and Jerry"
id.trakt_slug = "tom-and-jerry"
season = 1940
match.episode = "1:46"
type = "episode"

[[rules]]
match.title = "Tom and Jerry"
id.trakt_slug = "tom-and-jerry"
season = 1950
match.episode = "47:114"
episode_delta = -46
type = "episode"

[[rules]]
match.title = "Tom and Jerry"
id.trakt_slug = "tom-and-jerry"
season = 1960
match.episode = "115:161"
episode_delta = -114
type = "episode"
```
